export const TOGGLE_CART_DROPDOWN = 'TOGGLE_CART_DROPDOWN';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
export const DECREASE_ITEM = 'DECREASE_ITEM';

export const CLEAR_CART = 'CLEAR_CART';
