export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const TOGGLE_CART_DROPDOWN = 'TOGGLE_CART_DROPDOWN';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
export const DECREASE_ITEM = 'DECREASE_ITEM';

export const UPDATE_COLLECTIONS = 'UPDATE_COLLECTIONS';
